"""initial_schema

Revision ID: 253a384e4e6f
Revises: 
Create Date: 2025-03-29 17:51:16.103628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253a384e4e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='agents_ia'
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, schema='agents_ia')
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['agents_ia.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agents_ia'
    )
    op.create_index('idx_chat_history_character', 'chat_history', ['character_name'], unique=False, schema='agents_ia')
    op.create_index('idx_chat_history_created_at', 'chat_history', ['created_at'], unique=False, schema='agents_ia')
    op.create_index('idx_chat_history_session_id', 'chat_history', ['session_id'], unique=False, schema='agents_ia')
    op.create_index('idx_chat_history_user_id', 'chat_history', ['user_id'], unique=False, schema='agents_ia')
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['agents_ia.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agents_ia'
    )
    op.create_index('idx_sessions_token', 'sessions', ['token'], unique=False, schema='agents_ia')
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False, schema='agents_ia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_user_id', table_name='sessions', schema='agents_ia')
    op.drop_index('idx_sessions_token', table_name='sessions', schema='agents_ia')
    op.drop_table('sessions', schema='agents_ia')
    op.drop_index('idx_chat_history_user_id', table_name='chat_history', schema='agents_ia')
    op.drop_index('idx_chat_history_session_id', table_name='chat_history', schema='agents_ia')
    op.drop_index('idx_chat_history_created_at', table_name='chat_history', schema='agents_ia')
    op.drop_index('idx_chat_history_character', table_name='chat_history', schema='agents_ia')
    op.drop_table('chat_history', schema='agents_ia')
    op.drop_index('idx_users_email', table_name='users', schema='agents_ia')
    op.drop_table('users', schema='agents_ia')
    # ### end Alembic commands ###
